# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'akspool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'omeracraks.azurecr.io'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '9135e0b2-cfff-4136-bbbf-9c7428c2ba41'
    azureResourceGroup: 'aks-rg'
    kubernetesCluster: 'aks-test'
    command: 'apply'
    arguments: '-f deploy.yaml'
