# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'aks-agentpool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'iac-docker-sc'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'iac-aks-sc'
    azureResourceGroup: 'aks-rg'
    kubernetesCluster: 'aks-test'
    command: 'apply'
    arguments: '-f deploy.yaml'